"""Build the Apps Script schema snapshot from canonical repository artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SPIKE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = Path(__file__).resolve().parents[6]
SCHEMA_PATH = REPOSITORY_ROOT / "research/user-surveys/shared/schemas/survey-response.schema.json"
TAXONOMY_ROOT = REPOSITORY_ROOT / "research/user-surveys/shared/taxonomy"
OUTPUT_PATH = SPIKE_ROOT / "ContractSnapshot.gs"


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def assert_taxonomy_alignment(schema: dict) -> None:
    centres = load_json(TAXONOMY_ROOT / "centres.json")
    problems = load_json(TAXONOMY_ROOT / "problem-categories.json")
    channels = load_json(TAXONOMY_ROOT / "notification-channels.json")
    expected_centres = [item["centre_id"] for item in centres["centres"]]
    expected_centres += [item["centre_id"] for item in centres["system_options"]]
    expected_problems = [item["id"] for item in problems["problem_categories"]]
    expected_channels = [item["id"] for item in channels["notification_channels"]]
    answer_properties = schema["$defs"]["answers"]["properties"]
    checks = {
        "centre_ids": (answer_properties["centre_ids"]["items"]["enum"], expected_centres),
        "problem_category_ids": (answer_properties["problem_category_ids"]["items"]["enum"], expected_problems),
        "notification_channel_ids": (
            answer_properties["notification_channel_ids"]["items"]["enum"],
            expected_channels,
        ),
    }
    for name, (schema_values, taxonomy_values) in checks.items():
        if schema_values != taxonomy_values:
            raise SystemExit(f"Canonical schema/taxonomy drift for {name}")


def render_snapshot(schema: dict) -> str:
    metadata = {
        "contract_name": schema["x-contract-name"],
        "contract_version": schema["x-contract-version"],
        "survey_version": schema["x-survey-version"],
        "schema_id": schema["$id"],
        "generation_scope": "SPIKE_ONLY_CANONICAL_SCHEMA_SNAPSHOT",
    }
    return (
        "// Generated by tools/build_contract_snapshot.py from canonical repository artifacts.\n"
        "// Do not edit by hand. Regenerate and review before each experiment.\n"
        f"const CONTRACT_SNAPSHOT_METADATA = Object.freeze({json.dumps(metadata, ensure_ascii=False, indent=2)});\n"
        f"const CANONICAL_SURVEY_RESPONSE_SCHEMA = Object.freeze({json.dumps(schema, ensure_ascii=False, indent=2)});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write ContractSnapshot.gs")
    mode.add_argument("--check", action="store_true", help="verify ContractSnapshot.gs is current")
    args = parser.parse_args()
    schema = load_json(SCHEMA_PATH)
    assert_taxonomy_alignment(schema)
    rendered = render_snapshot(schema)
    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
        return 0
    if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
        raise SystemExit("ContractSnapshot.gs is missing or stale; run with --write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
